let menus = ['Pizza Giardino Esotico', 'Pizza Foresta Mistica','Pizza Seduzione Tropicale','Pizza Fusione Ardente','Pizza Sogno Orientale','Pizza L\'armonia dell\'Himalaya',
            'Mango Fuoco','Vaniglia Rosa','Tiramisù Pesca', 'Ebbrezza Cioccolato',
            'Lavendel-Limonade mit Chili','Zitronen-Thymian-Infusion'];

let data = {
    'shortName': ['giardino', 'foresta','tropicale','ardente','sogno','himalaya',
                  'mango_fuoco', 'vaniglia_rosa','tiramisù_pesca','ebbrezza_gioccolato',
                  'lavendel_limonade','zitronen_thymian'],
    'topping': ['Rucola, frische Erdbeeren, Ziegenkäse, Pinienkerne',
                'Waldpilze (wie Shiitake, Pfifferlinge), Trüffelöl, Mozzarella',
                'Hähnchen, Ananas, Mango, Kokosraspeln',
                'Chorizo, Jalapeños, Paprika, Manchego-Käse',
                'Gegrilltes Lamm, Auberginen, Feta, Minze',
                'Curry-Hühnchen, Kichererbsen, Spinat, Joghurtsauce',
                 null, null, null, null,
                 null,null],
    'sauce': ['Balsamico-Glasur', 'Schwarze Knoblauchcreme', 'Schwarze Knoblauchcreme', 'Chipotle-Tomatensauce','Tahini-Joghurt', 'Mango-Chutney',
               null, null,null, null,
               null,null],
    'description': ['Der Kontrast zwischen süßen Erdbeeren, würzigem Ziegenkäse und knusprigem Rucola verleiht dieser Pizza eine einzigartige Note',
                    'Diese Pizza bietet eine mysteriöse Mischung aus erdigen Aromen und dem Hauch von Trüffelöl.',
                    'Diese Pizza bietet eine mysteriöse Mischung aus erdigen Aromen und dem Hauch von Trüffelöl.',
                    'Für diejenigen, die es gerne etwas würziger mögen, bietet diese Pizza eine perfekte Mischung aus Schärfe und Aroma.',
                    'Diese Pizza bringt den Geschmack des Nahen Ostens mit zartem Lamm und erfrischenden Minznoten auf den Tisch.',
                    'Eine harmonische Fusion von würzigem Curry-Hühnchen, cremigen Kichererbsen, frischem Spinat und einer verführerischen Joghurtsauce. Eine köstliche Reise in die Aromen des Himalaya, die Ihren Gaumen verzaubert.',
                    'Ein leidenschaftliches Zusammenspiel von süßer Mango, einer Prise Peperoncino und unserer samtigen Gelato-Basis.',
                    'Vanillearoma trifft auf zartes Rosen-Sirup, um ein himmlisches Geschmackserlebnis auf unserer Gelato-Basis zu schaffen.',
                    'Erleben Sie den himmlischen Geschmack von frischen Pfirsichen, cremigem Mascarpone, luftigen Savoiardi, getränkt in Kaffee und bestäubt mit Kakao.',
                    'Ein berauschender Genuss aus dunkler Schokolade, knackigen Nüssen, süßem Honig und einem Hauch von Vanille',
                    'Eine erfrischende Limonade, veredelt mit Lavendelblüten und einer subtilen Schärfe von Chili. Ein unkonventioneller Twist für Limonadenliebhaber.',
                    'Eine warme Kräuterinfusion aus Zitronen und Thymian, die eine beruhigende und zugleich überraschende Geschmackskombination bietet.'],
    'price': ['9,50','10,00', '9,50', '11,50', '9,50', '12,00', '4,99', '4,99', '5,10', '5,30', '2,99','2,99'],
    'priceFloat': [9.50, 10.00, 9.50, 11.50, 9.50, 12.00, 4.99, 4.99, 5.10, 5.30, 2.99, 2.99]
}